import { useState, useEffect, useCallback } from "react";

// ── GoelStudio Architectural Showcase ───────────────────────────────────────
// 8 curated projects with real renderings. Editorial luxury aesthetic.
// Images expected in /public/images/ folder.

const PROJECTS = [
  {
    id: 1,
    title: "2-4 Union",
    subtitle: "Mixed-Use Tower",
    location: "Toronto, ON",
    year: "2024",
    phase: "Design Development",
    typology: "High-Rise Residential",
    area: "\u2014",
    description:
      "A sculpted residential tower rising from a transit-adjacent site. The faceted curtain wall catches light dynamically across the day, while a commercial podium anchors the building to the streetscape with active frontage and generous pedestrian realm.",
    metrics: [
      { label: "Type", value: "High-Rise" },
      { label: "Use", value: "Mixed" },
      { label: "Phase", value: "DD" },
      { label: "Location", value: "Toronto" },
    ],
    image: "/images/2-4union02.png",
    palette: ["#141a24", "#e2d5c3", "#b8956a", "#1e2530"],
    accent: "#b8956a",
  },
  {
    id: 2,
    title: "8 Mile Road",
    subtitle: "Custom Residence",
    location: "Ontario",
    year: "2023",
    phase: "Construction",
    typology: "Single-Family Residential",
    area: "\u2014",
    description:
      "A contemporary farmhouse composed of interlocking gabled volumes with standing-seam metal roofing and warm timber cladding. A central stone chimney anchors the composition, while generous glazing dissolves the boundary between interior and landscape.",
    metrics: [
      { label: "Type", value: "Custom" },
      { label: "Use", value: "Residential" },
      { label: "Phase", value: "CA" },
      { label: "Style", value: "Modern" },
    ],
    image: "/images/8mileroad.jpg",
    palette: ["#1a2218", "#ddd5c4", "#7a8b55", "#2a3328"],
    accent: "#7a8b55",
  },
  {
    id: 3,
    title: "126 Union",
    subtitle: "Master Plan",
    location: "Toronto, ON",
    year: "2024",
    phase: "Approvals",
    typology: "High-Rise Mixed-Use",
    area: "\u2014",
    description:
      "A two-tower residential development set within a tree-lined urban boulevard. The towers are differentiated in height and massing to create a dynamic skyline profile, unified by a shared podium with retail frontage and landscaped public realm.",
    metrics: [
      { label: "Type", value: "High-Rise" },
      { label: "Towers", value: "2" },
      { label: "Phase", value: "SPA" },
      { label: "Location", value: "Toronto" },
    ],
    image: "/images/126Union02.jpg",
    palette: ["#161c28", "#d4cfc8", "#6b7fa0", "#1e2636"],
    accent: "#6b7fa0",
  },
  {
    id: 4,
    title: "1055 Bloor",
    subtitle: "Mid-Rise Residential",
    location: "Toronto, ON",
    year: "2024",
    phase: "Design Development",
    typology: "Mid-Rise Residential + Commercial",
    area: "\u2014",
    description:
      "A contemporary mid-rise building with a composed facade of grey and charcoal panelling, punched balconies, and warm wood accent soffits at grade. The massing steps back at upper floors and activates the street corner with transparent commercial frontage.",
    metrics: [
      { label: "Type", value: "Mid-Rise" },
      { label: "Storeys", value: "6" },
      { label: "Phase", value: "DD" },
      { label: "Use", value: "Mixed" },
    ],
    image: "/images/1055-01.jpg",
    palette: ["#1a1c22", "#d8d0c6", "#8a8a98", "#26282e"],
    accent: "#8a8a98",
  },
  {
    id: 5,
    title: "Fieldway",
    subtitle: "Tower Cluster",
    location: "Toronto, ON",
    year: "2025",
    phase: "Schematic Design",
    typology: "High-Rise Master Plan",
    area: "\u2014",
    description:
      "A multi-tower master plan development featuring three slender residential towers rising from a lush parkland setting. The towers are staggered in height and orientation, framing views through the site while maximizing green space at grade.",
    metrics: [
      { label: "Type", value: "High-Rise" },
      { label: "Towers", value: "3+" },
      { label: "Phase", value: "SD" },
      { label: "Scale", value: "Master" },
    ],
    image: "/images/Fieldway02.jpeg",
    palette: ["#1a1e28", "#ddd4c4", "#c4935a", "#222838"],
    accent: "#c4935a",
  },
  {
    id: 6,
    title: "Glen Ave Concept",
    subtitle: "Sculptural Tower",
    location: "Toronto, ON",
    year: "2025",
    phase: "Concept Design",
    typology: "High-Rise Residential",
    area: "\u2014",
    description:
      "An organic, sculptural tower with a spiralling floor plate that rotates subtly as it rises. The sinuous form creates a distinctive silhouette on the skyline, with each unit benefiting from unique views generated by the building's continuous twist.",
    metrics: [
      { label: "Type", value: "High-Rise" },
      { label: "Form", value: "Organic" },
      { label: "Phase", value: "Concept" },
      { label: "Location", value: "Toronto" },
    ],
    image: "/images/Glen02.png",
    palette: ["#1e1a16", "#e0cdb8", "#a87040", "#2e2620"],
    accent: "#a87040",
  },
  {
    id: 7,
    title: "The Kingsway",
    subtitle: "Mid-Rise Residential",
    location: "Toronto, ON",
    year: "2022",
    phase: "Built",
    typology: "Mid-Rise Residential",
    area: "\u2014",
    description:
      "A completed mid-rise residential building featuring a bold, stacked massing with projecting balcony slabs that create deep horizontal shadow lines. The warm brick-toned accent panels contrast against the cool precast, giving the facade a layered, rhythmic quality.",
    metrics: [
      { label: "Type", value: "Mid-Rise" },
      { label: "Status", value: "Built" },
      { label: "Storeys", value: "8" },
      { label: "Location", value: "Toronto" },
    ],
    image: "/images/Kingway08.jpg",
    palette: ["#1c1820", "#ddd2c8", "#9a6858", "#2a2430"],
    accent: "#9a6858",
  },
  {
    id: 8,
    title: "York Mills",
    subtitle: "Commercial Mixed-Use",
    location: "Toronto, ON",
    year: "2024",
    phase: "Design Development",
    typology: "Commercial / Office",
    area: "\u2014",
    description:
      "A contemporary commercial development positioned along a major arterial, combining glass curtain wall office floors with warm cladding accents. The building engages the street with an activated public plaza, generous retail frontage, and a prominent signage tower element.",
    metrics: [
      { label: "Type", value: "Commercial" },
      { label: "Use", value: "Office" },
      { label: "Phase", value: "DD" },
      { label: "Location", value: "Toronto" },
    ],
    image: "/images/YM04.jpeg",
    palette: ["#1a1820", "#e0d0b8", "#c09040", "#282430"],
    accent: "#c09040",
  },
];

// ── Animated counter ────────────────────────────────────────────────────────
const AnimatedValue = ({ value, isVisible, delay = 0 }) => {
  const [display, setDisplay] = useState(value);
  const chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+-";

  useEffect(() => {
    if (!isVisible) return;
    let frame = 0;
    const maxFrames = 14;
    const timeout = setTimeout(() => {
      const interval = setInterval(() => {
        frame++;
        if (frame >= maxFrames) {
          setDisplay(value);
          clearInterval(interval);
          return;
        }
        setDisplay(
          value
            .split("")
            .map((ch, i) =>
              i < Math.floor((frame / maxFrames) * value.length)
                ? value[i]
                : chars[Math.floor(Math.random() * chars.length)]
            )
            .join("")
        );
      }, 40);
      return () => clearInterval(interval);
    }, delay);
    return () => clearTimeout(timeout);
  }, [isVisible, value]);

  return <span style={{ fontVariantNumeric: "tabular-nums" }}>{display}</span>;
};

// ── Grid overlay ────────────────────────────────────────────────────────────
const GridLines = ({ accent }) => (
  <div style={{ position: "absolute", inset: 0, pointerEvents: "none", opacity: 0.04, zIndex: 0 }}>
    {[20, 40, 60, 80].map((p) => (
      <div key={`v-${p}`} style={{ position: "absolute", left: `${p}%`, top: 0, bottom: 0, width: "1px", background: accent }} />
    ))}
    {[25, 50, 75].map((p) => (
      <div key={`h-${p}`} style={{ position: "absolute", top: `${p}%`, left: 0, right: 0, height: "1px", background: accent }} />
    ))}
  </div>
);

// ── Main Component ──────────────────────────────────────────────────────────
export default function ArchitecturalShowcase() {
  const [activeIndex, setActiveIndex] = useState(0);
  const [isRevealed, setIsRevealed] = useState(false);
  const [hoveredMetric, setHoveredMetric] = useState(null);
  const [imageLoaded, setImageLoaded] = useState(false);
  const [navHovered, setNavHovered] = useState(null);

  const project = PROJECTS[activeIndex];

  useEffect(() => {
    setIsRevealed(false);
    setImageLoaded(false);
    const t = setTimeout(() => setIsRevealed(true), 100);
    return () => clearTimeout(t);
  }, [activeIndex]);

  const goNext = useCallback(() => {
    setActiveIndex((i) => (i + 1) % PROJECTS.length);
  }, []);

  const goPrev = useCallback(() => {
    setActiveIndex((i) => (i - 1 + PROJECTS.length) % PROJECTS.length);
  }, []);

  useEffect(() => {
    const handler = (e) => {
      if (e.key === "ArrowRight" || e.key === "ArrowDown") goNext();
      if (e.key === "ArrowLeft" || e.key === "ArrowUp") goPrev();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [goNext, goPrev]);

  const ease = "cubic-bezier(0.22, 1, 0.36, 1)";

  return (
    <>
      <link
        href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400&family=DM+Mono:wght@300;400&display=swap"
        rel="stylesheet"
      />
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        html, body, #root { height: 100%; }
        ::selection { background: ${project.accent}40; color: ${project.palette[1]}; }
        @keyframes shimmer {
          0% { background-position: -200% 0; }
          100% { background-position: 200% 0; }
        }
      `}</style>

      <div
        style={{
          fontFamily: "'Cormorant Garamond', Georgia, serif",
          background: `linear-gradient(165deg, ${project.palette[0]} 0%, ${project.palette[3]} 40%, ${project.palette[0]} 100%)`,
          color: project.palette[1],
          minHeight: "100vh",
          position: "relative",
          overflow: "hidden",
          transition: `background 1.2s ${ease}, color 0.6s ease`,
          cursor: "crosshair",
        }}
      >
        {/* Grain */}
        <div
          style={{
            position: "fixed", inset: 0, pointerEvents: "none", zIndex: 100, opacity: 0.03,
            background: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.06'/%3E%3C/svg%3E")`,
          }}
        />

        <GridLines accent={project.accent} />

        {/* Header */}
        <header
          style={{
            position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
            display: "flex", justifyContent: "space-between", alignItems: "center",
            padding: "28px 48px", mixBlendMode: "difference",
          }}
        >
          <div style={{ fontSize: "14px", fontWeight: 300, letterSpacing: "0.35em", textTransform: "uppercase", opacity: 0.7 }}>
            GoelStudio
          </div>
          <div style={{ fontFamily: "'DM Mono', monospace", fontSize: "12px", letterSpacing: "0.2em", color: project.palette[2], opacity: 0.6 }}>
            {String(activeIndex + 1).padStart(2, "0")} / {String(PROJECTS.length).padStart(2, "0")}
          </div>
        </header>

        {/* Side text */}
        <div style={{ position: "fixed", left: "24px", top: "50%", transform: "translateY(-50%) rotate(-90deg)", fontFamily: "'DM Mono', monospace", fontSize: "9px", letterSpacing: "0.4em", color: project.palette[2], opacity: 0.2, textTransform: "uppercase", whiteSpace: "nowrap", zIndex: 50 }}>
          Selected Works &mdash; Portfolio
        </div>
        <div style={{ position: "fixed", right: "24px", top: "50%", transform: "translateY(-50%) rotate(90deg)", fontFamily: "'DM Mono', monospace", fontSize: "9px", letterSpacing: "0.4em", color: project.palette[2], opacity: 0.2, textTransform: "uppercase", whiteSpace: "nowrap", zIndex: 50 }}>
          {project.location} &mdash; {project.year}
        </div>

        {/* Main grid */}
        <main style={{ display: "grid", gridTemplateColumns: "1fr 1.2fr", minHeight: "100vh", position: "relative", zIndex: 1 }}>

          {/* Left: Content */}
          <section style={{ display: "flex", flexDirection: "column", justifyContent: "center", padding: "120px 56px 100px 64px" }}>
            <div style={{
              fontFamily: "'DM Mono', monospace", fontSize: "10px", letterSpacing: "0.4em", textTransform: "uppercase",
              color: project.accent, marginBottom: "16px",
              opacity: isRevealed ? 1 : 0, transform: isRevealed ? "translateY(0)" : "translateY(12px)",
              transition: `all 0.7s ${ease} 0.1s`,
            }}>
              {project.phase}
            </div>

            <h1 style={{
              fontSize: "clamp(44px, 5.5vw, 82px)", fontWeight: 300, lineHeight: 0.92, letterSpacing: "-0.03em", marginBottom: "8px",
              opacity: isRevealed ? 1 : 0, transform: isRevealed ? "translateY(0)" : "translateY(30px)",
              transition: `all 0.9s ${ease} 0.15s`,
            }}>
              {project.title}
            </h1>

            <p style={{
              fontSize: "clamp(15px, 1.6vw, 21px)", fontWeight: 300, fontStyle: "italic", color: project.palette[2], marginBottom: "36px",
              opacity: isRevealed ? 1 : 0, transform: isRevealed ? "translateY(0)" : "translateY(20px)",
              transition: `all 0.8s ${ease} 0.25s`,
            }}>
              {project.subtitle} &mdash; {project.typology}
            </p>

            <div style={{
              fontFamily: "'DM Mono', monospace", fontSize: "11px", letterSpacing: "0.15em", color: project.palette[2],
              display: "flex", gap: "28px", marginBottom: "28px",
              opacity: isRevealed ? 1 : 0, transform: isRevealed ? "translateY(0)" : "translateY(15px)",
              transition: `all 0.7s ${ease} 0.35s`,
            }}>
              <span>{project.location}</span>
              <span>{project.year}</span>
            </div>

            <div style={{
              width: isRevealed ? "80px" : "0px", height: "1px", background: project.accent, marginBottom: "28px",
              transition: `width 1s ${ease} 0.4s`,
            }} />

            <p style={{
              fontSize: "14.5px", lineHeight: 1.85, fontWeight: 300, maxWidth: "460px",
              opacity: isRevealed ? 0.75 : 0, transform: isRevealed ? "translateY(0)" : "translateY(20px)",
              transition: `all 0.8s ${ease} 0.45s`,
            }}>
              {project.description}
            </p>

            <div style={{
              display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 0, marginTop: "44px",
              borderTop: `1px solid ${project.accent}22`,
              opacity: isRevealed ? 1 : 0, transform: isRevealed ? "translateY(0)" : "translateY(20px)",
              transition: `all 0.7s ${ease} 0.55s`,
            }}>
              {project.metrics.map((m, idx) => (
                <div
                  key={m.label}
                  style={{
                    padding: "22px 0", textAlign: "center", cursor: "default",
                    borderRight: idx < 3 ? `1px solid ${project.accent}15` : "none",
                    background: hoveredMetric === idx ? `${project.accent}08` : "transparent",
                    transition: "background 0.3s ease",
                  }}
                  onMouseEnter={() => setHoveredMetric(idx)}
                  onMouseLeave={() => setHoveredMetric(null)}
                >
                  <div style={{ fontSize: "26px", fontWeight: 300, letterSpacing: "-0.02em", marginBottom: "6px" }}>
                    <AnimatedValue value={m.value} isVisible={isRevealed} delay={600 + idx * 80} />
                  </div>
                  <div style={{ fontFamily: "'DM Mono', monospace", fontSize: "9px", letterSpacing: "0.3em", textTransform: "uppercase", color: project.palette[2], opacity: 0.6 }}>
                    {m.label}
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Right: Image */}
          <section style={{ position: "relative", display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden" }}>
            <div style={{ position: "relative", width: "88%", maxWidth: "720px" }}>
              <span style={{
                position: "absolute", top: "-24px", right: "0",
                fontFamily: "'DM Mono', monospace", fontSize: "9px", letterSpacing: "0.3em",
                color: project.palette[2], opacity: 0.35, textTransform: "uppercase",
              }}>
                Exterior Rendering
              </span>

              <div style={{
                position: "relative", width: "100%", aspectRatio: "16 / 10",
                border: `1px solid ${project.accent}20`, overflow: "hidden",
                opacity: isRevealed ? 1 : 0,
                transform: isRevealed ? "scale(1) translateX(0)" : "scale(0.96) translateX(24px)",
                transition: `all 1s ${ease} 0.2s`,
              }}>
                {[
                  { top: "-4px", left: "-4px" },
                  { top: "-4px", right: "-4px" },
                  { bottom: "-4px", left: "-4px" },
                  { bottom: "-4px", right: "-4px" },
                ].map((pos, i) => (
                  <div key={i} style={{ position: "absolute", width: "8px", height: "8px", border: `1px solid ${project.accent}40`, ...pos, zIndex: 2 }} />
                ))}

                {!imageLoaded && (
                  <div style={{
                    position: "absolute", inset: 0, zIndex: 1,
                    background: `linear-gradient(90deg, ${project.palette[0]} 0%, ${project.palette[3]} 50%, ${project.palette[0]} 100%)`,
                    backgroundSize: "200% 100%",
                    animation: "shimmer 1.5s infinite",
                  }} />
                )}

                <img
                  src={project.image}
                  alt={project.title}
                  onLoad={() => setImageLoaded(true)}
                  style={{
                    width: "100%", height: "100%", objectFit: "cover", display: "block",
                    opacity: imageLoaded ? 1 : 0,
                    transform: imageLoaded ? "scale(1)" : "scale(1.05)",
                    transition: `all 0.8s ${ease}`,
                  }}
                />

                <div style={{
                  position: "absolute", inset: 0, pointerEvents: "none",
                  background: `radial-gradient(ellipse at center, transparent 50%, ${project.palette[0]}60 100%)`,
                }} />
              </div>
            </div>
          </section>
        </main>

        {/* Navigation label */}
        <div style={{
          position: "fixed", bottom: "72px", left: "50%", transform: "translateX(-50%)",
          fontFamily: "'DM Mono', monospace", fontSize: "9px", letterSpacing: "0.3em",
          color: project.palette[2], opacity: 0.3, textTransform: "uppercase", zIndex: 50,
        }}>
          {navHovered !== null ? PROJECTS[navHovered].title : "Navigate Projects"}
        </div>

        {/* Nav dots */}
        <nav style={{
          position: "fixed", bottom: "44px", left: "50%", transform: "translateX(-50%)",
          display: "flex", gap: "12px", alignItems: "center", zIndex: 50,
        }}>
          {PROJECTS.map((_, idx) => (
            <button
              key={idx}
              style={{
                width: idx === activeIndex ? "48px" : "12px", height: "3px",
                background: idx === activeIndex ? project.accent : `${project.palette[1]}30`,
                borderRadius: "1px", cursor: "pointer", border: "none", padding: 0,
                transition: `all 0.5s ${ease}`,
              }}
              onClick={() => setActiveIndex(idx)}
              onMouseEnter={() => setNavHovered(idx)}
              onMouseLeave={() => setNavHovered(null)}
              aria-label={`View ${PROJECTS[idx].title}`}
            />
          ))}
        </nav>

        {/* Arrow buttons */}
        <button onClick={goPrev} aria-label="Previous project"
          style={{
            position: "fixed", left: "48px", bottom: "40px", zIndex: 50,
            background: "none", border: `1px solid ${project.accent}30`, color: project.palette[1],
            width: "36px", height: "36px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center",
            fontFamily: "'DM Mono', monospace", fontSize: "14px", opacity: 0.5, transition: `all 0.3s ${ease}`,
          }}
          onMouseEnter={(e) => { e.target.style.opacity = "1"; e.target.style.borderColor = project.accent; }}
          onMouseLeave={(e) => { e.target.style.opacity = "0.5"; e.target.style.borderColor = `${project.accent}30`; }}
        >&#8592;</button>

        <button onClick={goNext} aria-label="Next project"
          style={{
            position: "fixed", right: "48px", bottom: "40px", zIndex: 50,
            background: "none", border: `1px solid ${project.accent}30`, color: project.palette[1],
            width: "36px", height: "36px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center",
            fontFamily: "'DM Mono', monospace", fontSize: "14px", opacity: 0.5, transition: `all 0.3s ${ease}`,
          }}
          onMouseEnter={(e) => { e.target.style.opacity = "1"; e.target.style.borderColor = project.accent; }}
          onMouseLeave={(e) => { e.target.style.opacity = "0.5"; e.target.style.borderColor = `${project.accent}30`; }}
        >&#8594;</button>
      </div>
    </>
  );
}
